[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = { path = "../scrap" }
sql = { path = "../sql" }

rocket = { version = "0.5.0" }
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
